// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfeQuvKwKKkGAQVVJchWLZBp_ln7wEhE',
    appId: '1:499712007929:web:67aef6bf5f125e7d8f0c28',
    messagingSenderId: '499712007929',
    projectId: 'instagram-2baf2',
    authDomain: 'instagram-2baf2.firebaseapp.com',
    storageBucket: 'instagram-2baf2.appspot.com',
    measurementId: 'G-KSTJ06KD4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcICRmdp3egE4O1N5bHJbpuRe2hgOgMxs',
    appId: '1:499712007929:android:cf80881ad300d1358f0c28',
    messagingSenderId: '499712007929',
    projectId: 'instagram-2baf2',
    storageBucket: 'instagram-2baf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR6GONapisGHxKdMLgSfu2R46D4HNrdGA',
    appId: '1:499712007929:ios:f884944f77798f3b8f0c28',
    messagingSenderId: '499712007929',
    projectId: 'instagram-2baf2',
    storageBucket: 'instagram-2baf2.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR6GONapisGHxKdMLgSfu2R46D4HNrdGA',
    appId: '1:499712007929:ios:f884944f77798f3b8f0c28',
    messagingSenderId: '499712007929',
    projectId: 'instagram-2baf2',
    storageBucket: 'instagram-2baf2.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHfeQuvKwKKkGAQVVJchWLZBp_ln7wEhE',
    appId: '1:499712007929:web:cd345bd9cc9486ce8f0c28',
    messagingSenderId: '499712007929',
    projectId: 'instagram-2baf2',
    authDomain: 'instagram-2baf2.firebaseapp.com',
    storageBucket: 'instagram-2baf2.appspot.com',
    measurementId: 'G-WPVW48KFTE',
  );
}
